### ISSUE TITLE
Error in password_verify

### ISSUE THREAD

**Issue by JoshuaWarror** [pH-7/PHP-MVC-Blog-System#1]
I installed this and it worked right away, that is until I tried the login.  I struggled with it for awhile as the login failed with "Incorrect Login!" message.  As I dug into the code I found a posting about the use of "password_verify."  It made it clear that un-encrypted password from the form needed to be the first parameter in the function's argument list.  I swapped the encrypted password with the form's input password and it worked right away.   

 if(password_verify($_POST['password'], $sDbPassword ))

**Comment by pH-7** [comment]
Good catch! Fixed in https://github.com/pH-7/PHP-MVC-Blog-System/commit/984085264c444a1f7c26f83ee68a778aab7bf3ee

Thanks!
