### ISSUE TITLE
You should add Comments

### ISSUE THREAD

**Issue by halojoy** [pH-7/PHP-MVC-Blog-System#4]
It is very good code.
I like it.
Next step would add a comments feature.
Think the script deserves this.

**Comment by pH-7** [comment]
> It is very good code.
> I like it.
> Next step would add a comments feature.
> Think the script deserves this.

Thank you for your suggestion @halojoy! Absolutely. Feel free to raise a PR if you feel like adding it. I will then be more than happy to review your pull request.
